package net.jahhan.constant.enumeration;

/**
 * @author nince
 */
public enum FieldTypeEnum {
	BIGDECIMAL,TYINT, INT, BOOLEAN, SMALL_INT, BIG_INT, DOUBLE, CHAR8, CHAR32, CHAR24, CHAR11, CHAR36, CHAR64, CHAR128, CHAR512, CHAR1024, CHAR2048, CHAR65535, DATE, DATETIME, DATE_OR_EMPTY, DATETIME_OR_EMPTY, TIME, LIST, MAP, OBJECT, NULL
}
